import type { Case } from '@/types';

export const mockCases: Case[] = [
  {
    id: 'CASE001',
    lawyerId: 'LAWYER01',
    clientInfo: {
      name: 'Alice Johnson',
      phone: '+1-202-555-0182',
      email: 'alice.j@example.com',
      location: 'New York, NY',
    },
    caseDetails: {
      type: 'Divorce',
      description: 'Client is seeking to file for divorce from her spouse of 5 years. The main points of contention are asset division and child custody.',
      urgency: 'high',
      estimatedValue: 250000,
      documents: [{ name: 'Marriage Certificate.pdf', url: '#' }, { name: 'Asset List.docx', url: '#' }],
      timeline: 'Events leading to the separation occurred over the last 6 months.',
    },
    aiAnalysis: {
      summary: 'A standard divorce case with complexities in asset division and custody. The client has a clear timeline and documentation, which is a strong starting point.',
      strengths: ['Clear documentation', 'Client has a specific goal', 'No history of domestic violence reported'],
      weaknesses: ['High-value assets may lead to prolonged negotiation', 'Potential for custody battle'],
      recommendations: 'Advise the client on mediation as a first step to reduce costs. Gather all financial statements from both parties. Prepare for a contested custody hearing.',
      successProbability: 75,
      estimatedDuration: '9-12 months',
      complexity: 'medium',
    },
    conversation: {
      messages: [
        { sender: 'client', message: 'Hello, I need help with a divorce.', timestamp: new Date('2023-10-01T10:00:00Z'), type: 'text' },
        { sender: 'ai', message: 'Hello Alice. I can help with that. To start, what type of legal problem are you facing?', timestamp: new Date('2023-10-01T10:01:00Z'), type: 'text' },
        { sender: 'client', message: 'I need to file for divorce.', timestamp: new Date('2023-10-01T10:02:00Z'), type: 'text' },
        { sender: 'ai', message: 'I understand. When did the key events related to this take place?', timestamp: new Date('2023-10-01T10:03:00Z'), type: 'text' },
        { sender: 'client', message: 'It\'s been happening over the last 6 months.', timestamp: new Date('2023-10-01T10:04:00Z'), type: 'text' },
      ],
      status: 'completed',
    },
    lawyerDecision: {
      status: 'accepted',
      decision: 'Accepting the case. Seems straightforward. High value.',
      timestamp: new Date('2023-10-02T09:00:00Z'),
      notes: 'Initial consultation scheduled for next week. Sent engagement letter.',
    },
    createdAt: new Date('2023-10-01T10:00:00Z'),
    updatedAt: new Date('2023-10-02T09:00:00Z'),
  },
  {
    id: 'CASE002',
    lawyerId: 'LAWYER01',
    clientInfo: {
      name: 'Bob Williams',
      phone: '+1-202-555-0191',
      email: 'bob.w@example.com',
      location: 'Los Angeles, CA',
    },
    caseDetails: {
      type: 'Personal Injury',
      description: 'Client was involved in a car accident and sustained injuries. The other driver ran a red light. Client has medical bills and lost wages.',
      urgency: 'high',
      estimatedValue: 75000,
      documents: [{ name: 'Police Report.pdf', url: '#' }, { name: 'Medical Bills.zip', url: '#' }],
      timeline: 'Accident occurred on September 15, 2023.',
    },
    aiAnalysis: {
      summary: 'A personal injury case stemming from a car accident where the other party was at fault according to the police report. The client has documented injuries and financial loss.',
      strengths: ['Clear liability based on police report', 'Documented medical expenses and lost wages', 'No prior injuries of the same nature'],
      weaknesses: ['Insurance company may dispute the severity of injuries', 'Client took 3 days to see a doctor'],
      recommendations: 'File a claim with the other driver\'s insurance immediately. Gather all medical records and employment history. Do not accept the first settlement offer.',
      successProbability: 90,
      estimatedDuration: '6-9 months',
      complexity: 'simple',
    },
    conversation: {
      messages: [
        { sender: 'client', message: 'I was in a car accident and need a lawyer.', timestamp: new Date('2023-10-03T14:00:00Z'), type: 'text' },
        { sender: 'ai', message: 'I\'m sorry to hear that. I can help guide you. Have you consulted with other lawyers about this matter?', timestamp: new Date('2023-10-03T14:01:00Z'), type: 'text' },
        { sender: 'client', message: 'No, you are the first.', timestamp: new Date('2023-10-03T14:02:00Z'), type: 'text' },
      ],
      status: 'completed',
    },
    lawyerDecision: {
      status: 'pending',
      decision: '',
      timestamp: new Date(),
      notes: '',
    },
    createdAt: new Date('2023-10-03T14:00:00Z'),
    updatedAt: new Date('2023-10-03T14:00:00Z'),
  },
  {
    id: 'CASE003',
    lawyerId: 'LAWYER01',
    clientInfo: {
      name: 'Charlie Brown',
      phone: '+1-202-555-0143',
      email: 'charlie.b@example.com',
      location: 'Chicago, IL',
    },
    caseDetails: {
      type: 'Labor Law',
      description: 'Client believes he was wrongfully terminated from his job after reporting a safety violation.',
      urgency: 'medium',
      estimatedValue: 120000,
      documents: [{ name: 'Termination Letter.pdf', url: '#' }, { name: 'Safety Report Email.eml', url: '#' }],
      timeline: 'Reported violation on Aug 1st, terminated on Aug 15th.',
    },
    aiAnalysis: {
      summary: 'Potential whistleblower retaliation case. The proximity between the safety report and termination is a strong indicator. Case value is significant due to potential damages.',
      strengths: ['Close timing between protected activity and adverse action', 'Written evidence of the safety report'],
      weaknesses: ['Employer may claim termination was for performance reasons', 'Need to find evidence of pretext'],
      recommendations: 'File a complaint with the appropriate labor board. Conduct discovery to find evidence of pretext. Interview other employees if possible.',
      successProbability: 65,
      estimatedDuration: '12-18 months',
      complexity: 'complex',
    },
    conversation: {
      messages: [
        { sender: 'client', message: 'I think I was fired illegally.', timestamp: new Date('2023-10-04T11:00:00Z'), type: 'text' },
        { sender: 'ai', message: 'I see. Can you tell me what happened?', timestamp: new Date('2023-10-04T11:01:00Z'), type: 'text' },
      ],
      status: 'ongoing',
    },
    lawyerDecision: {
      status: 'pending',
      decision: '',
      timestamp: new Date(),
      notes: '',
    },
    createdAt: new Date('2023-10-04T11:00:00Z'),
    updatedAt: new Date('2023-10-04T11:00:00Z'),
  },
  {
    id: 'CASE004',
    lawyerId: 'LAWYER01',
    clientInfo: {
      name: 'Diana Prince',
      phone: '+1-202-555-0177',
      email: 'diana.p@example.com',
      location: 'Washington, D.C.',
    },
    caseDetails: {
      type: 'Contract Dispute',
      description: 'A freelance designer, client was not paid for a completed project. The contract is clear on payment terms.',
      urgency: 'low',
      estimatedValue: 15000,
      documents: [{ name: 'Contract.pdf', url: '#' }, { name: 'Final Deliverables.zip', url: '#' }],
      timeline: 'Project completed 60 days ago, payment was due 30 days ago.',
    },
aiAnalysis: {
      summary: 'A straightforward breach of contract case. The client has a signed contract and proof of work delivery. The amount is relatively small, suggesting small claims court might be an option.',
      strengths: ['Signed written contract', 'Proof of deliverable submission', 'Clear payment terms'],
      weaknesses: ['Client may argue work was not up to standard', 'Low value might not justify full litigation costs'],
      recommendations: 'Send a formal demand letter as the first step. If no response, consider filing in small claims court to minimize costs. Advise client on the cost-benefit of pursuing the claim.',
      successProbability: 95,
      estimatedDuration: '3-6 months',
      complexity: 'simple',
    },
    conversation: {
      messages: [
        { sender: 'client', message: 'My client refuses to pay me for my work.', timestamp: new Date('2023-10-05T16:00:00Z'), type: 'text' },
      ],
      status: 'ongoing',
    },
    lawyerDecision: {
      status: 'rejected',
      decision: 'Value too low for our firm.',
      timestamp: new Date('2023-10-06T10:00:00Z'),
      notes: 'Referred client to a small claims advisory service.',
    },
    createdAt: new Date('2023-10-05T16:00:00Z'),
    updatedAt: new Date('2023-10-06T10:00:00Z'),
  },
];
