import type { Case } from '@/types';

export const mockCases: Case[] = [
  {
    id: 'CASO001',
    lawyerId: 'ABOGADO01',
    clientInfo: {
      name: 'Alicia Johnson',
      phone: '+1-202-555-0182',
      email: 'alicia.j@ejemplo.com',
      location: 'Nueva York, NY',
    },
    caseDetails: {
      type: 'Divorcio',
      description: 'La clienta busca solicitar el divorcio de su cónyuge de 5 años. Los principales puntos de discordia son la división de bienes y la custodia de los hijos.',
      urgency: 'alta',
      estimatedValue: 250000,
      documents: [{ name: 'Certificado de Matrimonio.pdf', url: '#' }, { name: 'Lista de Bienes.docx', url: '#' }],
      timeline: 'Los eventos que llevaron a la separación ocurrieron en los últimos 6 meses.',
    },
    aiAnalysis: {
      summary: 'Un caso de divorcio estándar con complejidades en la división de bienes y la custodia. La clienta tiene una cronología clara y documentación, lo cual es un punto de partida sólido.',
      strengths: ['Documentación clara', 'La clienta tiene un objetivo específico', 'No hay historial de violencia doméstica reportado'],
      weaknesses: ['Los bienes de alto valor pueden llevar a una negociación prolongada', 'Posibilidad de una batalla por la custodia'],
      recommendations: 'Aconsejar a la clienta sobre la mediación como primer paso para reducir costos. Recopilar todos los estados financieros de ambas partes. Prepararse para una audiencia de custodia disputada.',
      successProbability: 75,
      estimatedDuration: '9-12 meses',
      complexity: 'media',
    },
    conversation: {
      messages: [
        { sender: 'client', message: 'Hola, necesito ayuda con un divorcio.', timestamp: new Date('2023-10-01T10:00:00Z'), type: 'text' },
        { sender: 'ai', message: 'Hola Alicia. Puedo ayudar con eso. Para empezar, ¿qué tipo de problema legal enfrenta?', timestamp: new Date('2023-10-01T10:01:00Z'), type: 'text' },
        { sender: 'client', message: 'Necesito solicitar el divorcio.', timestamp: new Date('2023-10-01T10:02:00Z'), type: 'text' },
        { sender: 'ai', message: 'Entiendo. ¿Cuándo ocurrieron los eventos clave relacionados con esto?', timestamp: new Date('2023-10-01T10:03:00Z'), type: 'text' },
        { sender: 'client', message: 'Ha estado sucediendo durante los últimos 6 meses.', timestamp: new Date('2023-10-01T10:04:00Z'), type: 'text' },
      ],
      status: 'completado',
    },
    lawyerDecision: {
      status: 'aceptado',
      decision: 'Aceptando el caso. Parece sencillo. Alto valor.',
      timestamp: new Date('2023-10-02T09:00:00Z'),
      notes: 'Consulta inicial programada para la próxima semana. Se envió la carta de compromiso.',
    },
    createdAt: new Date('2023-10-01T10:00:00Z'),
    updatedAt: new Date('2023-10-02T09:00:00Z'),
  },
  {
    id: 'CASO002',
    lawyerId: 'ABOGADO01',
    clientInfo: {
      name: 'Roberto Williams',
      phone: '+1-202-555-0191',
      email: 'roberto.w@ejemplo.com',
      location: 'Los Ángeles, CA',
    },
    caseDetails: {
      type: 'Lesiones Personales',
      description: 'El cliente estuvo involucrado en un accidente de coche y sufrió lesiones. El otro conductor se pasó un semáforo en rojo. El cliente tiene facturas médicas y salarios perdidos.',
      urgency: 'alta',
      estimatedValue: 75000,
      documents: [{ name: 'Informe Policial.pdf', url: '#' }, { name: 'Facturas Médicas.zip', url: '#' }],
      timeline: 'El accidente ocurrió el 15 de septiembre de 2023.',
    },
    aiAnalysis: {
      summary: 'Un caso de lesiones personales derivado de un accidente de tráfico donde la otra parte fue culpable según el informe policial. El cliente ha documentado lesiones y pérdidas económicas.',
      strengths: ['Responsabilidad clara basada en el informe policial', 'Gastos médicos y salarios perdidos documentados', 'Sin lesiones previas de la misma naturaleza'],
      weaknesses: ['La compañía de seguros puede disputar la gravedad de las lesiones', 'El cliente tardó 3 días en ver a un médico'],
      recommendations: 'Presentar una reclamación al seguro del otro conductor de inmediato. Recopilar todos los registros médicos y el historial laboral. No aceptar la primera oferta de acuerdo.',
      successProbability: 90,
      estimatedDuration: '6-9 meses',
      complexity: 'simple',
    },
    conversation: {
      messages: [
        { sender: 'client', message: 'Tuve un accidente de coche y necesito un abogado.', timestamp: new Date('2023-10-03T14:00:00Z'), type: 'text' },
        { sender: 'ai', message: 'Lamento oír eso. Puedo guiarte. ¿Has consultado a otros abogados sobre este asunto?', timestamp: new Date('2023-10-03T14:01:00Z'), type: 'text' },
        { sender: 'client', message: 'No, usted es el primero.', timestamp: new Date('2023-10-03T14:02:00Z'), type: 'text' },
      ],
      status: 'completado',
    },
    lawyerDecision: {
      status: 'pendiente',
      decision: '',
      timestamp: new Date(),
      notes: '',
    },
    createdAt: new Date('2023-10-03T14:00:00Z'),
    updatedAt: new Date('2023-10-03T14:00:00Z'),
  },
  {
    id: 'CASO003',
    lawyerId: 'ABOGADO01',
    clientInfo: {
      name: 'Carlos Brown',
      phone: '+1-202-555-0143',
      email: 'carlos.b@ejemplo.com',
      location: 'Chicago, IL',
    },
    caseDetails: {
      type: 'Derecho Laboral',
      description: 'El cliente cree que fue despedido injustamente de su trabajo después de reportar una violación de seguridad.',
      urgency: 'media',
      estimatedValue: 120000,
      documents: [{ name: 'Carta de Despido.pdf', url: '#' }, { name: 'Email de Informe de Seguridad.eml', url: '#' }],
      timeline: 'Reportó la violación el 1 de agosto, fue despedido el 15 de agosto.',
    },
    aiAnalysis: {
      summary: 'Posible caso de represalia por denuncia. La proximidad entre el informe de seguridad y el despido es un fuerte indicador. El valor del caso es significativo debido a los posibles daños.',
      strengths: ['Proximidad temporal entre la actividad protegida y la acción adversa', 'Evidencia escrita del informe de seguridad'],
      weaknesses: ['El empleador puede alegar que el despido fue por razones de rendimiento', 'Necesidad de encontrar pruebas de pretexto'],
      recommendations: 'Presentar una queja ante la junta laboral correspondiente. Realizar un descubrimiento para encontrar pruebas de pretexto. Entrevistar a otros empleados si es posible.',
      successProbability: 65,
      estimatedDuration: '12-18 meses',
      complexity: 'compleja',
    },
    conversation: {
      messages: [
        { sender: 'client', message: 'Creo que me despidieron ilegalmente.', timestamp: new Date('2023-10-04T11:00:00Z'), type: 'text' },
        { sender: 'ai', message: 'Entiendo. ¿Puede contarme qué pasó?', timestamp: new Date('2023-10-04T11:01:00Z'), type: 'text' },
      ],
      status: 'en curso',
    },
    lawyerDecision: {
      status: 'pendiente',
      decision: '',
      timestamp: new Date(),
      notes: '',
    },
    createdAt: new Date('2023-10-04T11:00:00Z'),
    updatedAt: new Date('2023-10-04T11:00:00Z'),
  },
  {
    id: 'CASO004',
    lawyerId: 'ABOGADO01',
    clientInfo: {
      name: 'Diana Prince',
      phone: '+1-202-555-0177',
      email: 'diana.p@ejemplo.com',
      location: 'Washington, D.C.',
    },
    caseDetails: {
      type: 'Disputa de Contrato',
      description: 'Una diseñadora freelance, a la clienta no se le pagó por un proyecto completado. El contrato es claro en los términos de pago.',
      urgency: 'baja',
      estimatedValue: 15000,
      documents: [{ name: 'Contrato.pdf', url: '#' }, { name: 'Entregables Finales.zip', url: '#' }],
      timeline: 'Proyecto completado hace 60 días, el pago vencía hace 30 días.',
    },
    aiAnalysis: {
      summary: 'Un caso de incumplimiento de contrato sencillo. La clienta tiene un contrato firmado y prueba de la entrega del trabajo. El monto es relativamente pequeño, lo que sugiere que el tribunal de reclamos menores podría ser una opción.',
      strengths: ['Contrato escrito firmado', 'Prueba de la entrega de los entregables', 'Términos de pago claros'],
      weaknesses: ['El cliente puede argumentar que el trabajo no cumplió con los estándares', 'El bajo valor podría no justificar los costos completos del litigio'],
      recommendations: 'Enviar una carta de demanda formal como primer paso. Si no hay respuesta, considerar presentar una demanda en el tribunal de reclamos menores para minimizar costos. Asesorar a la clienta sobre el costo-beneficio de seguir con la reclamación.',
      successProbability: 95,
      estimatedDuration: '3-6 meses',
      complexity: 'simple',
    },
    conversation: {
      messages: [
        { sender: 'client', message: 'Mi cliente se niega a pagarme por mi trabajo.', timestamp: new Date('2023-10-05T16:00:00Z'), type: 'text' },
      ],
      status: 'en curso',
    },
    lawyerDecision: {
      status: 'rechazado',
      decision: 'El valor es demasiado bajo para nuestro bufete.',
      timestamp: new Date('2023-10-06T10:00:00Z'),
      notes: 'Se remitió a la clienta a un servicio de asesoría de reclamos menores.',
    },
    createdAt: new Date('2023-10-05T16:00:00Z'),
    updatedAt: new Date('2023-10-06T10:00:00Z'),
  },
];
